name: Manual File Selection and Merge

on:
  workflow_dispatch:

jobs:
  select-and-merge:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Get diverge commit
        id: diverge-commit
        run: |
          DIVERGE=$(git merge-base origin/QA origin/integration)
          echo "::set-output name=diverge_commit::$DIVERGE"
          
      - name: Get changed files
        id: changed-files
        run: |
          FILES_CHANGED=$(git diff --name-only ${{ steps.diverge-commit.outputs.diverge_commit }} HEAD)
          echo "::set-output name=files_changed::$FILES_CHANGED"
      
      - name: Display changed files
        run: |
          echo "Files changed since diverge: ${{ steps.changed-files.outputs.files_changed }}"
      
      - name: Create a pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: integration
          title: 'Merge selected files from QA branch'
          body: |
            Please review the changes below and merge if everything looks good.
            
            Changes:
            ${{ steps.changed-files.outputs.files_changed }}
          labels: 'automated'
